<a href="https://colab.research.google.com/github/LucasPequenoSterzeck/Data_Visualization/blob/main/PyTorch_Jovian_ZeroToGANs/pytorch_ztog_attachment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pytorch-ztog-attachment-1

Here's the assingment that's I've recieve in first class of "Deep Learning with PyTorch: Zero to GANs"

# Attachment 01 - PyTorch Zero to GANN's



## Questions for Review

Try answering the following questions to test your understanding of the topics covered in this notebook:

1. What is a linear regression model? Give an example of a problem formulated as a linear regression model.
>Um problema de regressão linear é um problema aonde conseguimos traçar uma correlação entre as variáveis independentes de uma forma a correlacioná-las com a nossa variável alvo/target.<br>
2. What are input and target variables in a dataset? Give an example.
> **Input's:** São variáveis independentes que comportam o modelo (Ex: Ao avaliar uma colheita de cana de açucar temos como variáveis independentes (Input's) a umidade do solo, clima do período entre-safra, relação de pragas por hectar...)<br>**Target:** É a variável que queremos prever (Ex: Considerando uma colheita de cana podemos querer prever variáveis como tonelada por hectar ou nível de qualidade do açucar coletado da cana).<br>
3. What are weights and biases in a linear regression model?
> **Weights:** São os pesos que o modelo irá com muito esforço procurar encontrar entre as variáveis independentes e variável target, esses pesos tendem a iniciar de forma aleatória e conforme a função de custo escolhida e treinamento do modelo, os weights serão cada vez mais próximos da realidade de importancia das variáveis para a predição do objetivo.<br>**Biases:** É o ponto de partida de onde o modelo deve estipular a predição, digamos que em uma colhetia de cana não seja possível existir uma "colheita negativa de cana", o Bias irá nos ajudar com essa correção.
4. How do you represent tabular data using PyTorch tensors?
> Normalmente são representadas por meio de matrizes multidimensionais.
5. Why do we create separate matrices for inputs and targets while training a linear regression model?
> Basta declará-los de forma separada ou atribuí-los em variáveis diferentes, se forem importados via matrix Numpy fica ainda mais fácil utilizando o método slice com colchetes.
6. How do you determine the shape of the weights matrix & bias vector given some training data?
> Cada variável que queremos prever(target) terá seu conjunto de pesos que serão multiplicados pelas variáveis e então será somado o bias.
7. How do you create randomly initialized weights & biases with a given shape?
> basta utilizar torch.randn(shapre_of,tensor)
8. How is a linear regression model implemented using matrix operations? Explain with an example.
> Irei utilizar o exemplo fornecido em aula para melhor elucidar o cálculo..:
![Imagem de exemplo](https://i.imgur.com/WGXLFvA.png)
<br>Seria utilizado a operação de Matrix @ entre matrizes para a seguinte operação: 1ª Linha 'w1' : 73 * w11 + 67 * w12 + 43 * w13 + b1
9. How do you generate predictions using a linear regression model?
> As previsão são realizadas quando multiplicamos os pesos respectivos das variáveis independentes fornecidas e então adicionados bias para chegar ao valor que o modelo irá prever.
10. Why are the predictions of a randomly initialized model different from the actual targets?
> Porque os valores de weight's e Bia's que foram informados de forma aleatória dificilmente vão ser aqueles que melhor espelham a devida correlação das variáveis individuais para seu alvo.
11. What is a loss function? What does the term “loss” signify?
> Uma função de custo serve paa nos mostrar o quanto errado nosso modelo está, e também é o parâmetros base para conseguirmos quantificar o erro em relação a direção das variáveis(weights) que iremos alterar (acrescentar ou subtrair) para então minimizar o erro e chegar em previsões mais próximas do real.
12. What is mean squared error?
> Mean Squared Error ou Erro Médio Quadrático é uma medida utilizada quando se quer saber em um plano quadrático o quanto nossa previsão está longe do real cenário, de forma bem simplificada, ela funciona quando pegamos o valor real e o correlacionamos com o valor previsto do modelo.
13. Write a function to calculate mean squared using model predictions and actual targets.
> Feito em notebook auxiliar anterior.
14. What happens when you invoke the `.backward` function on the result of the mean squared error loss function?
> É usada para calcular os gradientes em relação aos parâmetros do modelo, permitindo a aplicação do algoritmo de otimização, como o Gradiente Descendente, para atualizar os pesos da rede neural durante o processo de treinamento.
15. Why is the derivative of the loss w.r.t. the weights matrix itself a matrix? What do its elements represent?
> A derivada da perda em relação à matriz de pesos é uma matriz porque ela captura a sensibilidade da perda em relação a cada peso na matriz. Seus elementos representam a contribuição de cada peso para a perda geral.
16. How is the derivate of the loss w.r.t. a weight element useful for reducing the loss? Explain with an example.
> A derivada da perda em relação a um elemento de peso indica como uma pequena mudança nesse peso afeta a perda. Ao ajustar o peso na direção oposta à sua derivada, podemos reduzir iterativamente a perda.
17. Suppose the derivative  of the loss w.r.t. a weight element is positive. Should you increase or decrease the element’s value slightly to get a lower loss?
> Se a derivada for positiva, diminuir o peso diminuirá a perda, e vice-versa.
18. Suppose the derivative  of the loss w.r.t. a weight element is negative. Should you increase or decrease the element’s value slightly to get a lower loss?
> Se a derivada for negativa, aumentar o peso diminuirá a perda, e vice-versa.
19. How do you update the weights and biases of a model using their respective gradients to reduce the loss slightly?
> Para darmos passo pequenos utilizamops uma taxa de aprendizagem bem pequena, dessa forma evitamos de dar passos grandes na direção errada.
20. What is the gradient descent optimization algorithm? Why is it called “gradient descent”?
> A descida de gradiente é a computação em sequẽncia do erro em sua descida ao custo da função objetivando que este seja cada vez menor, dito isso, quanto mais optimizado for nosso algoritmito de gradient descent mais rápido será a nossa "descida" para o custo mínimo de erro da função.
21. Why do you subtract a “small quantity” proportional to the gradient from the weights & biases, not the actual gradient itself?
> Conforme citado acima, para evitar que os passos que estamos tomando acabem levando o modelo para um caminho errado.
22. What is learning rate? Why is it important?
> É a taxa na qual iremos acatar a direção que a função de perca e descida de gradiente.
23. What is `torch.no_grad`?
> Desativa o cálculo automático de gradientes.
24. Why do you reset gradients to zero after updating weights and biases?
> Ao redefinir os gradientes para zero, garantimos que não haja acumulação indesejada de gradientes de iterações anteriores, permitindo um cálculo correto dos gradientes na próxima iteração. Essa etapa é fundamental para o bom funcionamento do algoritmo de otimização usado para treinar o modelo.
25. What are the steps involved in training a linear regression model using gradient descent?
> Realizar as operação de dados, pesos e bias, computar erro, computar gradiente, zerar gradiente, e então voltar ao começo...
26. What is an epoch?
> É uma única passagem completa pelo conjunto de treinamento, onde cada amostra do conjunto de dados é apresentada uma vez ao modelo.
27. What is the benefit of training a model for multiple epochs?
> Treinar um modelo por várias épocas permite que o modelo aprenda gradualmente padrões mais complexos nos dados e ajuste seus pesos de forma mais precisa, levando a uma melhor capacidade de generalização e desempenho do modelo.
28. How do you make predictions using a trained model?
> Para conseguir previsões utilizando um modelo somente precisamos multiplicar os pesos pelas variáveis independentes e somar o bias.
29. What should you do if your model’s loss doesn’t decrease while training? Hint: learning rate.
> Considerando que a dica foi learning rate, podemos pressupor que o modelo não está conseguindo reduzir a perca devido ao lerning rate atual estar muito alto ou ainda muito baixo, seria ideal alterá-lo e então observar o que ocorre com o custo da função.
30. What is `torch.nn`?
> É um módulo que fornece as ferramentas e classes necessárias para criar e treinar redes neurais
31. What is the purpose of the `TensorDataset` class in PyTorch? Give an example.
> Facilizar a segmentação da parte de treino e teste, além de manipular os dados de forma intuitiva e possibilitar também p shufle(aleatoriedade) na sequência dos dados.
32. What is a data loader in PyTorch? Give an example.
> Um data loader no PyTorch é um objeto que facilita o carregamento de dados em lotes durante o treinamento de modelos. Por exemplo, podemos criar um data loader para carregar um conjunto de dados de imagens, permitindo iterar sobre ele em lotes.
33. How do you use a data loader to retrieve batches of data?
> Para recuperar lotes de dados usando um data loader, podemos iterar sobre ele em um loop e obter um lote de cada vez. Por exemplo, usando um loop for batch in data_loader, podemos acessar os dados do lote dentro do loop.
34. What are the benefits of shuffling the training data before creating batches?
> Embaralhar os dados de treinamento antes de criar lotes ajuda a evitar que o modelo aprenda viéses indesejados ou padrões sequenciais e facilita a generalização para novos dados.
35. What is the benefit of training in small batches instead of training with the entire dataset?
> Treinar em lotes pequenos permite atualizações mais frequentes dos pesos do modelo, levando a uma convergência mais rápida e uso eficiente da memória.
36. What is the purpose of the `nn.Linear` class in PyTorch? Give an example.
> A classe **nn.Linear** é usada para definir uma **camada linear** em uma rede neural. Por exemplo, nn.Linear(10, 5) cria uma camada linear que mapeia 10 entradas para 5 saídas.
37. How do you see the weights and biases of a `nn.Linear` model?
> model.parameters()
38. What is the purpose of the `torch.nn.functional` module?
> Contém funções de ativação, funções de perda e outras operações comuns usadas na construção de redes neurais.
39. How do you compute mean squared error loss using a PyTorch built-in function?
> MSELoss()
40. What is an optimizer in PyTorch?
> Um optimizador será o cálculo que realizara a descida do gradiente.
41. What is `torch.optim.SGD`? What does SGD stand for?
> SGD é uma forma eficiente de realizar a descida de gradiente, seu significado é Stochastic Gradient Descent
42. What are the inputs to a PyTorch optimizer?
> Taxa de aprendizado é algo em comum, mas cada optimizador poderá oferecer mais critérios e configurações de acordo com seu objetivo.
43. Give an example of creating an optimizer for training a linear regression model.
> optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
44. Write a function to train a `nn.Linear` model in batches using gradient descent.
> def train_model(model, dataloader, optimizer, loss_fn):
        for inputs, labels in dataloader:
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = loss_fn(outputs, labels)
            loss.backward()
            optimizer.step()

45. How do you use a linear regression model to make predictions on previously unseen data?
> predicted_values = model(new_data)


Agora irei dedicar a escrita em inglês...

# Top 5 must now tensor functions

As we describe above, tensors are matrices that's we manipulate trow the code using the pytorch lib, so let's now more about some functions that can manipulate tensors

In [24]:
# Let's firs create 2 tensors for examples:
import torch
import numpy as np

tA = torch.tensor([[1,2],
                   [2,3],
                   [3,4.]], requires_grad=True)

tB = torch.tensor([[2,2],
                   [2,2],
                   [2,2.]], requires_grad=True)

print(f'-> Tensors:\n\nTensor A: \n{tA}\n\nTensor B: \n{tB}')

-> Tensors:

Tensor A: 
tensor([[1., 2.],
        [2., 3.],
        [3., 4.]], requires_grad=True)

Tensor B: 
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)


-----------------------------------
# [TORCH.TENSOR.POW](https://pytorch.org/docs/stable/generated/torch.Tensor.pow.html#torch.Tensor.pow)

Tensor.pow(exponent)

In [11]:
# Tensor.pow is used to exponent calculations, such as below;

tA.pow(2)

tensor([[ 1.,  4.],
        [ 4.,  9.],
        [ 9., 16.]], grad_fn=<PowBackward0>)

In [13]:
tB.pow(3)

tensor([[8., 8.],
        [8., 8.],
        [8., 8.]], grad_fn=<PowBackward0>)

-----------------------------------
# [TORCH.TENSOR.POW_](https://pytorch.org/docs/stable/generated/torch.Tensor.pow_.html#torch.Tensor.pow_)

Tensor.pow_(exponent)

In PyTorch, Tensor.pow() and Tensor.pow_() are two different methods for exponentiation.

This method returns a new tensor with each element raised to the power of the given exponent.
The original tensor remains unchanged.

Here's a simple example to illustrate the difference:

In [32]:
import torch

tP = torch.tensor([2, 3, 4.])

# Using Tensor.pow()
result = tP.pow(2)
print('Original tensor(tP) in POW function equals =', result)
print('Original tesnor(tP) without any function equals =',tP)

# Using Tensor.pow_()
tP.pow_(2)
print('\nBut when we use the POW_ function, the original variable(tP) change the inner values in the exponencial =',tP)


Original tensor(tP) in POW function equals = tensor([ 4.,  9., 16.])
Original tesnor(tP) without any function equals = tensor([2., 3., 4.])

But when we use the POW_ function, the original variable(tP) change the inner values in the exponencial = tensor([ 4.,  9., 16.])


**IMPORTANTE NOTE!** To use pow_ we cannot use tesnors with requires_grad=True.

-----------------------------------
# [TORCH.TENSOR.QSCHEME](https://pytorch.org/docs/stable/generated/torch.Tensor.qscheme.html#torch.Tensor.qscheme)

Tensor.qscheme() → torch.qscheme

Returns the quantization scheme of a given QTensor.

Importante Note about this function: The qscheme() method is specifically designed to retrieve the quantization scheme of a quantized tensor (QTensor). In order to use qscheme(), you need to have a tensor that has undergone quantization using PyTorch's quantization functions.

So befor we use the QSCHEME() we need to use:
## [TORCH.TENSOR.QUANTIZE_PER_TENSOR](https://pytorch.org/docs/stable/generated/torch.quantize_per_tensor.html)
The torch.quantize_per_tensor() function is one of the methods available in PyTorch to quantize a tensor. It applies per-tensor quantization by determining a scaling factor (scale) and zero point (zero_point) to represent the tensor's values within a reduced range.
> In the practive: torch.quantize_per_tensor just turn each value into INT type

In [49]:
# Quantize the tensor
scale = 0.1
zero_point = 0
quantized_tensor = torch.quantize_per_tensor(tA, scale, zero_point, dtype=torch.quint8)

# Get the quantization SCHEME
qscheme = quantized_tensor.qscheme()
print(qscheme)  # Output: torch.per_tensor_affine

# Additional operations based on the quantization scheme
if qscheme == torch.per_tensor_affine:
    print("This is a per-tensor affine quantized tensor.")
elif qscheme == torch.per_channel_affine:
    print("This is a per-channel affine quantized tensor.")

torch.per_tensor_affine
This is a per-tensor affine quantized tensor.


**Note:** "affine" indicates that the quantization scheme uses an affine transformation to map floating-point values to quantized integer values

-----------------------------------
# [TORCH.TENSOR.RESHAPE](https://pytorch.org/docs/stable/generated/torch.Tensor.reshape.html#torch.Tensor.reshape)

Tensor.reshape(*shape) → Tensor

Returns a tensor with the same data and number of elements as self but with the specified shape. This method returns a view if shape is compatible with the current shape. See torch.Tensor.view() on when it is possible to return a view.

In [52]:
tX = tA.reshape([2,3])

print(f'This is the original tensor(tA)\n{tA}\nWith Shape: {tA.shape}\n\nThis is the new reshaped tensor(tX):\n{tX}\nWith the new shape: {tX.shape}')

This is the original tensor(tA)
tensor([[1., 2.],
        [2., 3.],
        [3., 4.]], requires_grad=True)
With Shape: torch.Size([3, 2])

This is the new reshaped tensor(tX):
tensor([[1., 2., 2.],
        [3., 3., 4.]], grad_fn=<ReshapeAliasBackward0>)
With the new shape: torch.Size([2, 3])


In [53]:
# Other apliccation in reshape():

tY = tB.reshape([6,1])

print(f'This is the original tensor(tB)\n{tB}\nWith Shape: {tB.shape}\n\nThis is the new reshaped tensor(tY):\n{tY}\nWith the new shape: {tY.shape}')

This is the original tensor(tB)
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)
With Shape: torch.Size([3, 2])

This is the new reshaped tensor(tY):
tensor([[2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.]], grad_fn=<ReshapeAliasBackward0>)
With the new shape: torch.Size([6, 1])


-----------------------------------
# [TORCH.TENSOR.ROUND](https://pytorch.org/docs/stable/generated/torch.Tensor.round.html#torch.Tensor.round)

Tensor.round(decimals=0) → Tensor

Simply round the values of the tensor, let's aplly:

In [58]:
ten = torch.tensor([1.154,2.895,6.748496])
print('Original tensor: ', ten)

tenn = ten.round(decimals=2)
print('\nNew tensor: ', tenn)

Original tensor:  tensor([1.1540, 2.8950, 6.7485])

New tensor:  tensor([1.1500, 2.9000, 6.7500])


-----------------------------------
# [TORCH.TENSOR.SPLIT](https://pytorch.org/docs/stable/generated/torch.Tensor.split.html#torch.Tensor.split)

Tensor.split(split_size, dim=0)



In [74]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('Original tensor: ',tensor,'\n')

# Split the tensor into chunks of size 3
chunks = torch.split(tensor, 3)

# Print the resulting chunks
for i,chunk in enumerate(chunks, start=1):
    print(f"{i}º Chunk: {chunk}")


Original tensor:  tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 

1º Chunk: tensor([1, 2, 3])
2º Chunk: tensor([4, 5, 6])
3º Chunk: tensor([7, 8, 9])
4º Chunk: tensor([10])


In [80]:
# Now let's aplly the same function but in tensor B:
print('Original tensor(tB): \n',tB,'\n')

# Split the tensor into chunks of size 1 along dimension 0
chunks = torch.split(tB, 1, dim=0)

# Print the resulting chunks
for i,chunk in enumerate(chunks, start=1):
    print(f"{i}º Chunk: {chunk}")

Original tensor(tB): 
 tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True) 

1º Chunk: tensor([[2., 2.]], grad_fn=<SplitBackward0>)
2º Chunk: tensor([[2., 2.]], grad_fn=<SplitBackward0>)
3º Chunk: tensor([[2., 2.]], grad_fn=<SplitBackward0>)
